# Generated by Django 4.0.3 on 2022-04-05 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'to do'), (2, 'on going'), (3, 'done')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('attendees', models.PositiveIntegerField(default=0)),
                ('event_date', models.DateField()),
                ('notes', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.client')),
                ('event_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.status')),
                ('support_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.supportcontact')),
            ],
        ),
    ]
